version: "3.7"

services:
  opg-sirius-header:
    build:
      context: .
      dockerfile: docker/opg-sirius-header/Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - type: bind
        source: ./sirius-header.js
        target: /app/public/js/sirius-header.js

  cypress:
    build:
      context: .
      dockerfile: docker/cypress/Dockerfile
    depends_on:
      - opg-sirius-header
