version: "3.6"

services:
  sirius-header:
    build:
      context: ..
      dockerfile: ./docker/sirius-header/Dockerfile
    ports: ["8889:3456"]
    environment:
      PREFIX: /supervision
      SIRIUS_PUBLIC_URL: http://localhost:8080